### PR TITLE
Unified style

### PR DESCRIPTION
**Pull request by vpiili**
Now this is just better headerComponent. In the future this might translate to Asteriski's own component library, who knows.

### CODE REVIEW

**Comment by aegan123** [comment]
We don't use bootstrap. 

Final look and feel is still in progress by graphical experts so soloing on look & feel is not a good idea.

**Comment by vpiili** [comment]
> We don't use bootstrap.

And why is that exactly?

> Final look and feel is still in progress by graphical experts so soloing on look & feel is not a good idea.

I dont think that reusing existing component is soloing, plus after storybook and proper component library changing look and feel is easier.

**Comment by vpiili** [comment]
Screenshot 2023-02-20 at 10 54 33
Screenshot 2023-02-20 at 10 55 29

**Comment by aegan123** [comment]
> > We don't use bootstrap.
> 
> And why is that exactly?
> 
> > Final look and feel is still in progress by graphical experts so soloing on look & feel is not a good idea.
> 
> I dont think that reusing existing component is soloing, plus after storybook and proper component library changing look and feel is easier.

Then you should also communicate this to the others involved in the project.

**Pull request merged**
