### PR TITLE
Added own types package and exported types from it

### PR DESCRIPTION
**Pull request by vpiili**

### CODE REVIEW

**Comment by aegan123** [comment]
Add SignupEvent and ArchivedEvent types as well.

**Comment by aegan123** [comment]
And maybe all other types that are sent/received to/from the backend.

**Comment by vpiili** [comment]
> And maybe all other types that is sent/received to/from the backend.

Right now that is just a simple template file. Those types can be exported at will when needed.

**Review by aegan123 — CHANGES_REQUESTED** [review]
All types coming from/going to backend should be available.

**Comment by vpiili** [comment]
> All types coming from/going to backend should be available.

They are available, one can import them directly from `@asteriskiry_eventsignup-types` package. This is just a helper file.

**Review by aegan123 — APPROVED** [review]

**Pull request merged**
