### PR TITLE
Add login/logout functionality

### LINKED ISSUE #3: Add Login/logout functionality
Add a page for login form and a page logout. 

Use basic http auth at first. If it doesn't work something else, like JWT, is needed (requires modification to the backend as well).

### PR DESCRIPTION
**Pull request by aegan123**
Add the possibility that a user can login/logout. Including all related functionalities. Resolves #3 .

### CODE REVIEW

**Comment by aegan123** [comment]
On hold for now.

**Comment by vpiili** [comment]
This should be rebased onto develop.

**Comment by aegan123** [comment]
Logout needs fixing still. Need to handle the new cookie based method.

**Comment by aegan123** [comment]
Superseced by Keycloak.

**Pull request closed without merging**
